<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.chromia</groupId>
        <artifactId>chromia-parent</artifactId>
        <version>0.2.0</version>
    </parent>

    <groupId>net.postchain</groupId>
    <artifactId>vector-db-chromia-extension</artifactId>
    <version>${revision}</version>

    <name>vector-db-chromia-extension</name>
    <description>Extensions to Postchain for Postgres Vector support</description>

    <properties>
        <revision>dev</revision>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <kotlin.version>2.0.0</kotlin.version>
        <kotlin.compiler.jvmTarget>21</kotlin.compiler.jvmTarget>
        <kotlin.code.style>obsolete</kotlin.code.style> <!-- Kotlin obsolete IntelliJ IDEA codestyle -->

        <postchain.version>3.47.1</postchain.version>
        <postchain-chromia.version>3.35.4</postchain-chromia.version>

        <!-- Tests -->
        <directory.chain.version>1.91.0</directory.chain.version>
        <directory.source>${project.build.directory}/directory-chain/src</directory.source>
        <directory.config>${project.basedir}/src/test/resources/net/postchain/images/directory1/directory1.yml</directory.config>
        <rell.maven.plugin.version>0.14.9</rell.maven.plugin.version>

        <junit.version>5.9.1</junit.version>
        <testcontainers.version>1.20.3</testcontainers.version>

        <!--suppress UnresolvedMavenProperty -->
        <gitlab.username>${CI_REGISTRY_USER}</gitlab.username>
        <!--suppress UnresolvedMavenProperty -->
        <gitlab.password>${CI_REGISTRY_PASSWORD}</gitlab.password>
        <gitlab.registry>registry.gitlab.com/chromaway/core/vector-db-extension</gitlab.registry>
        <docker.cache>/tmp/docker-cache</docker.cache>
        <image.platforms>linux/amd64,linux/arm64</image.platforms>
        <image.name>chromaway/vector-db-extension-chromia-subnode</image.name>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain</artifactId>
                <version>${postchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.postchain</groupId>
                <artifactId>postchain-chromia</artifactId>
                <version>${postchain-chromia.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>${testcontainers.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-spi</artifactId>
        </dependency>

        <dependency>
            <groupId>net.postchain.images</groupId>
            <artifactId>chromia-subnode</artifactId>
            <version>${postchain-chromia.version}</version>
        </dependency>

        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>chromia-infrastructure</artifactId>
            <version>${postchain-chromia.version}</version>
        </dependency>

        <dependency>
            <groupId>io.github.microutils</groupId>
            <artifactId>kotlin-logging-jvm</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>deployment-test</artifactId>
            <version>${postchain-chromia.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit-pioneer</groupId>
            <artifactId>junit-pioneer</artifactId>
            <version>1.7.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain</groupId>
            <artifactId>postchain-devtools</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>jdbc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.postchain.client</groupId>
            <artifactId>chromia-client</artifactId>
            <version>3.26.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Needed for testcontainers -->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.3</version>
                <configuration>
                    <allowInsecureRegistries>false</allowInsecureRegistries>
                    <from>
                        <image>registry.gitlab.com/chromaway/core-tools/chromia-images/java21-postgres16-ubuntu:1.1.1@sha256:55159e183db72134d4ef37e54f79549c3108df4bc54dde2040bdaa130e601fa5</image>
                    </from>
                    <to>
                        <image>${image.name}</image>
                    </to>
                    <container>
                        <appRoot>/opt/chromaway/postchain</appRoot>
                        <workingDirectory>/opt/chromaway/postchain</workingDirectory>
                        <entrypoint>/bin/bash</entrypoint>
                        <args>entrypoint.sh</args>
                        <environment>
                            <POSTCHAIN_RUNNING_IN_CONTAINER>true</POSTCHAIN_RUNNING_IN_CONTAINER>
                            <LOG4J_CONFIGURATION_FILE>/opt/chromaway/postchain/log4j2.yml</LOG4J_CONFIGURATION_FILE>
                            <POSTCHAIN_DIR>/opt/chromaway/postchain</POSTCHAIN_DIR>
                            <PGDATA>/var/lib/postgresql/data</PGDATA>
                            <POSTGRES_DB>postchain</POSTGRES_DB>
                            <POSTGRES_USER>postchain</POSTGRES_USER>
                            <POSTGRES_PASSWORD>postchain</POSTGRES_PASSWORD>
                            <POSTGRES_INITDB_ARGS>--lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8</POSTGRES_INITDB_ARGS>
                        </environment>
                        <creationTime>${git.commit.time}</creationTime> <!-- populated by git-commit-id-plugin -->
                        <filesModificationTime>${git.commit.time}</filesModificationTime> <!-- populated by git-commit-id-plugin -->
                    </container>
                    <containerizingMode>packaged</containerizingMode>
                </configuration>
                <executions>
                    <execution>
                        <id>docker-tar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>buildTar</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>docker-build</id>
                        <phase>pre-integration-test</phase> <!-- needed in integration tests -->
                        <goals>
                            <goal>dockerBuild</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <environmentVariables>
                        <DIST_EXECUTABLE>
                            ${project.build.directory}/${project.artifactId}-${project.version}-dist/management-console/bin/bad
                        </DIST_EXECUTABLE>
                        <PROJECT_VERSION>${project.version}</PROJECT_VERSION>
                        <TESTCONTAINERS_RYUK_DISABLED>true</TESTCONTAINERS_RYUK_DISABLED>
                        <POSTCHAIN_TEST_DOCKER_IMAGE_POSTCHAIN_SERVER>registry.gitlab.com/chromaway/postchain-chromia/chromaway/chromia-server:latest-snapshot</POSTCHAIN_TEST_DOCKER_IMAGE_POSTCHAIN_SERVER>
                    </environmentVariables>
                    <includes>
                        <include>**/*IT.*</include>
                        <include>**/*SlowIntegrationTest.*</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <id>integration-test</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>integration-test</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>verify</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>net.postchain.rell</groupId>
                <artifactId>rell-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>vector-example-install</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>rell-install</goal>
                        </goals>
                        <configuration>
                            <configPath>${project.basedir}/rell/chromia.yml</configPath>
                            <source>${project.basedir}/rell/src</source>
                            <target>${project.build.directory}/test-classes/chains/</target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>vector-example-compile</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>rell-compile</goal>
                        </goals>
                        <configuration>
                            <configPath>${project.basedir}/rell/chromia.yml</configPath>
                            <source>${project.basedir}/rell/src</source>
                            <target>${project.build.directory}/test-classes/chains/</target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>vector-example-gen-client</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>rell-generate-client</goal>
                        </goals>
                        <configuration>
                            <packageName>net.postchain.gtx.extensions.vectordb</packageName>
                            <source>rell/src</source>
                            <target>${project.build.directory}/generated-test-sources/net/postchain/gtx/extensions/vectordb/</target>
                            <force>true</force>
                            <mainModules>
                                <mainModule>vector_example</mainModule>
                                <mainModule>integration_test.vector_example_test</mainModule>
                                <mainModule>integration_test.query_compute</mainModule>
                            </mainModules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-test-sources</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <environmentVariables>
                                <!-- Set our subnode to use the daemon user and group. This will be accepted by initdb
                                since the user exists in the host mounted /etc/passwd file. -->
                                <POSTCHAIN_SUBNODE_USER>1:1</POSTCHAIN_SUBNODE_USER>
                            </environmentVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>artifact</id>
            <activation>
                <activeByDefault>true</activeByDefault>
                <property>
                    <name>!local</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-scm-plugin</artifactId>
                        <version>1.11.2</version>
                        <executions>
                            <execution>
                                <id>d1-resources</id>
                                <phase>initialize</phase>
                                <goals>
                                    <goal>checkout</goal>
                                </goals>
                                <configuration>
                                    <connectionUrl>scm:git:https://gitlab.com/chromaway/core/directory-chain.git
                                    </connectionUrl>
                                    <checkoutDirectory>${project.build.directory}/directory-chain</checkoutDirectory>
                                    <scmVersion>${directory.chain.version}</scmVersion>
                                    <scmVersionType>tag</scmVersionType>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>local</id>
            <activation>
                <property>
                    <name>local</name>
                </property>
            </activation>
            <properties>
                <directory.source>${project.basedir}/../directory-chain/src</directory.source>
                <directory.config>${project.basedir}/../directory-chain/chromia.yml</directory.config>
            </properties>
        </profile>
        <profile>
            <id>docker-arm</id>
            <activation>
                <os>
                    <family>mac</family>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>com.google.cloud.tools</groupId>
                            <artifactId>jib-maven-plugin</artifactId>
                            <configuration>
                                <from>
                                    <platforms>
                                        <platform>
                                            <os>linux</os>
                                            <architecture>arm64</architecture>
                                        </platform>
                                    </platforms>
                                </from>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
        <profile>
            <id>docker-push</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                                <configuration>
                                    <from>
                                        <platforms>
                                            <platform>
                                                <architecture>amd64</architecture>
                                                <os>linux</os>
                                            </platform>
                                            <platform>
                                                <architecture>arm64</architecture>
                                                <os>linux</os>
                                            </platform>
                                        </platforms>
                                    </from>
                                    <to>
                                        <image>${gitlab.registry}/${image.name}:${project.version}</image>
                                        <auth>
                                            <username>${env.CI_REGISTRY_USER}</username>
                                            <password>${env.CI_REGISTRY_PASSWORD}</password>
                                        </auth>
                                    </to>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>chromia-parent</id>
            <name>Chromia parent GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/50818999/packages/maven</url>
        </repository>
        <repository>
            <id>postchain</id>
            <name>Postchain GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/32294340/packages/maven</url>
        </repository>
        <repository>
            <id>rell</id>
            <name>Rell Registry</name>
            <url>https://gitlab.com/api/v4/projects/32802097/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-client</id>
            <name>Postchain Client GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/46288950/packages/maven</url>
        </repository>
        <repository>
            <id>postchain-chromia</id>
            <name>Postchain chromia GitLab Registry</name>
            <url>https://gitlab.com/api/v4/projects/33481005/packages/maven</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>rellmaven</id>
            <url>https://gitlab.com/api/v4/projects/37668820/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <distributionManagement>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
        </repository>
        <snapshotRepository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/projects/${env.CI_PROJECT_ID}/packages/maven</url>
        </snapshotRepository>
    </distributionManagement>
</project>
